package wooteco.subway;

import static org.assertj.core.api.Assertions.assertThat;

import io.restassured.RestAssured;
import io.restassured.response.ExtractableResponse;
import io.restassured.response.Response;
import org.junit.jupiter.api.BeforeEach;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.web.server.LocalServerPort;
import org.springframework.test.annotation.DirtiesContext;
import org.springframework.test.context.ActiveProfiles;
import wooteco.subway.exception.SubwayExceptionSetInterface;

@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)
@DirtiesContext(classMode = DirtiesContext.ClassMode.BEFORE_EACH_TEST_METHOD)
@ActiveProfiles("test")
public class AcceptanceTest {

    @LocalServerPort
    int port;

    @BeforeEach
    public void setUp() {
        RestAssured.port = port;
    }

    protected void 에러가_발생한다(ExtractableResponse<Response> response,
        SubwayExceptionSetInterface subwayExceptionSetInterface) {
        assertThat(response.statusCode()).isEqualTo(subwayExceptionSetInterface.status());
        assertThat(response.body().asString()).isEqualTo(subwayExceptionSetInterface.message());
    }
}
